import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { ScrollView, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

const AMBER  = "#FFA12B";
const MUTED  = "rgba(255,255,255,0.5)";
const BORDER = "rgba(255,255,255,0.08)";

function Section({ title, children }) {
  return (
    <View style={{ marginBottom: 36 }}>
      <View style={{ flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 }}>
        <View style={{ width: 3, height: 16, borderRadius: 2, backgroundColor: AMBER }} />
        <Text style={{ color: "#fff", fontSize: 18, fontWeight: "700" }}>{title}</Text>
      </View>
      {children}
    </View>
  );
}

function P({ children }) {
  return <Text style={{ color: MUTED, fontSize: 15, lineHeight: 26, marginBottom: 12 }}>{children}</Text>;
}

function Bullet({ children }) {
  return (
    <View style={{ flexDirection: "row", gap: 10, marginBottom: 8 }}>
      <Text style={{ color: AMBER, fontSize: 15, marginTop: 1 }}>•</Text>
      <Text style={{ color: MUTED, fontSize: 15, lineHeight: 24, flex: 1 }}>{children}</Text>
    </View>
  );
}

export default function TermsPage() {
  const router = useRouter();
  const insets = useSafeAreaInsets();

  return (
    <View style={{ flex: 1, backgroundColor: "#12161F" }}>
      {/* Header */}
      <LinearGradient colors={["#1A1F2E", "#12161F"]}
        style={{ paddingTop: insets.top + 16, paddingHorizontal: 24, paddingBottom: 24, borderBottomWidth: 1, borderBottomColor: BORDER }}>
        <TouchableOpacity onPress={() => router.back()} style={{ marginBottom: 16 }}>
          <Text style={{ color: AMBER, fontSize: 14, fontWeight: "600" }}>← Back</Text>
        </TouchableOpacity>
        <View style={{ flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 6 }}>
          <LinearGradient colors={[AMBER, "#D97706"]}
            style={{ width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" }}>
            <Text style={{ fontSize: 18 }}>📋</Text>
          </LinearGradient>
          <Text style={{ color: "#fff", fontSize: 26, fontWeight: "900", letterSpacing: -0.5 }}>Terms of Service</Text>
        </View>
        <Text style={{ color: MUTED, fontSize: 13 }}>Last updated: August 1, 2026</Text>
      </LinearGradient>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: 24, maxWidth: 720, width: "100%", alignSelf: "center" }}>

        <P>Welcome to FixFromPix. By downloading, installing, or using our application, you agree to be bound by these Terms of Service. Please read them carefully.</P>

        <Section title="1. Acceptance of Terms">
          <P>By accessing or using FixFromPix ("the App"), you agree to these Terms of Service and our Privacy Policy. If you do not agree, do not use the App. These terms apply to all users, including those who access the App without an account.</P>
        </Section>

        <Section title="2. Description of Service">
          <P>FixFromPix is an AI-powered property inspection tool that allows users to photograph repair issues and receive estimated repair costs. The App is designed for informational and planning purposes only.</P>
          <P>FixFromPix is intended for use by:</P>
          <Bullet>Real estate investors, contractors, landlords, property managers, and homeowners.</Bullet>
          <Bullet>Any individual or professional who needs to assess property repair costs.</Bullet>
        </Section>

        <Section title="3. User Accounts">
          <P>To use the full features of FixFromPix, you must create an account. You agree to:</P>
          <Bullet>Provide accurate and complete registration information.</Bullet>
          <Bullet>Keep your password secure and confidential.</Bullet>
          <Bullet>Notify us immediately of any unauthorized use of your account.</Bullet>
          <Bullet>Be responsible for all activity that occurs under your account.</Bullet>
          <P>We reserve the right to terminate accounts that violate these Terms.</P>
        </Section>

        <Section title="4. AI-Generated Estimates — Important Disclaimer">
          <P>ALL COST ESTIMATES PROVIDED BY FIXFROMPIX ARE GENERATED BY ARTIFICIAL INTELLIGENCE AND ARE FOR INFORMATIONAL PURPOSES ONLY.</P>
          <Bullet>Estimates are not professional appraisals, inspections, or contractor bids.</Bullet>
          <Bullet>Actual repair costs may vary significantly based on location, materials, labor rates, and conditions not visible in photos.</Bullet>
          <Bullet>FixFromPix does not guarantee the accuracy, completeness, or reliability of any AI-generated estimate.</Bullet>
          <Bullet>Always consult a licensed contractor or inspector before making financial decisions based on App estimates.</Bullet>
          <P>You assume all risk associated with reliance on AI-generated cost estimates.</P>
        </Section>

        <Section title="5. User Content">
          <P>You retain ownership of all photos and content you upload to FixFromPix. By uploading content, you grant FixFromPix a limited license to process, store, and display that content solely to provide the App's services to you.</P>
          <P>You agree not to upload content that:</P>
          <Bullet>Is illegal, harmful, or violates any third-party rights.</Bullet>
          <Bullet>Contains personal information of others without their consent.</Bullet>
          <Bullet>Is intended to abuse, spam, or exploit the service.</Bullet>
        </Section>

        <Section title="6. Acceptable Use">
          <P>You agree to use FixFromPix only for lawful purposes. You must not:</P>
          <Bullet>Attempt to reverse engineer, decompile, or hack the App.</Bullet>
          <Bullet>Use the App to collect data about other users.</Bullet>
          <Bullet>Interfere with or disrupt the App's infrastructure.</Bullet>
          <Bullet>Use automated tools to scrape or extract data from the App.</Bullet>
          <Bullet>Resell or redistribute access to the App without our written consent.</Bullet>
        </Section>

        <Section title="7. Intellectual Property">
          <P>All content, branding, logos, design, code, and features of FixFromPix are the intellectual property of FixFromPix and its licensors. You may not copy, modify, distribute, or create derivative works without our express written permission.</P>
        </Section>

        <Section title="8. Limitation of Liability">
          <P>TO THE MAXIMUM EXTENT PERMITTED BY LAW, FIXFROMPIX SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES, ARISING FROM YOUR USE OF THE APP OR RELIANCE ON ITS AI-GENERATED CONTENT.</P>
          <P>Our total liability to you for any claim arising from these Terms or your use of the App shall not exceed the amount you paid us in the 12 months preceding the claim.</P>
        </Section>

        <Section title="9. Indemnification">
          <P>You agree to indemnify and hold harmless FixFromPix, its officers, employees, and partners from any claims, damages, or expenses (including attorney's fees) arising from your use of the App, your violation of these Terms, or your violation of any third-party rights.</P>
        </Section>

        <Section title="10. Modifications to the Service">
          <P>We reserve the right to modify, suspend, or discontinue any part of FixFromPix at any time, with or without notice. We will not be liable to you or any third party for any such changes.</P>
        </Section>

        <Section title="11. Governing Law">
          <P>These Terms shall be governed by and construed in accordance with the laws of the State of Florida, United States, without regard to its conflict of law provisions. Any disputes shall be resolved in the courts of Florida.</P>
        </Section>

        <Section title="12. Changes to These Terms">
          <P>We may update these Terms from time to time. We will notify you of material changes via email or an in-app notification. Your continued use of FixFromPix after changes take effect constitutes your acceptance of the new Terms.</P>
        </Section>

        <Section title="13. Contact Us">
          <P>If you have any questions about these Terms, please contact us:</P>
          <Bullet>Email: support@fixfrompix.app</Bullet>
          <Bullet>Website: fixfrompix.app</Bullet>
        </Section>

        <View style={{ height: insets.bottom + 40 }} />
      </ScrollView>
    </View>
  );
}
